// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOs8soMBWTeENQonoS20trYYOhztOvDc',
    appId: '1:482984678027:android:4f9ff3f03c073536f3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    storageBucket: 'login-otp-9cd84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3w8FJl2o2UOJ4l14SpXTjTETgmuoApqk',
    appId: '1:482984678027:ios:deadd32c10cd9635f3ba8e',
    messagingSenderId: '482984678027',
    projectId: 'login-otp-9cd84',
    storageBucket: 'login-otp-9cd84.appspot.com',
    androidClientId: '482984678027-o6r423rrnie6i0ge0lm8ks12mqpndtub.apps.googleusercontent.com',
    iosClientId: '482984678027-3ddfkvist3u01rbe9g2puqbkp9nqiuo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.heartDiseasePrediction',
  );
}
